name: Python application test

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
      run: |
        python -m pytest
